services:
  - type: web
    name: google-trends-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.80 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11